/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-18 07:28:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import com.oreilly.servlet.MultipartRequest;

public final class ex16_005fok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//인코딩 설정 -> 한글 지원 위해서
	request.setCharacterEncoding("UTF-8");
	
	//<form enctype="multipart/form-data">을 적용하면, 인코딩 방식이 변경
	//1. request.getParameter() 동작 불가능
	//2. request.getParameterValues() 동작 불가능
	
	//cos.jar > MultiparatRequest 클래스 -> 객체가 request의 수신 기능을 대신함
	
	//String name = request.getParameter("name");
	//String age = request.getParameter("age");
	
	//업로드된 파일을 어디에 저장할지 경로 지정 -> webapp/files -> 로컬경로(c://~~~)
	//C:\class\code\server\JSPTest\src\main\webapp\files
	
	//절대경로(상대경로) -> 로컬경로로 변환해주는 고마운 소스
	String path = application.getRealPath("/files");
	//C:\class\code\server\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\JSPTest\files
	//System.out.println(path);
	
	//업로드할 파일의 최대 크기 제한 -> 바이트 단위
	int size = 1024*1024*100;		//100MB
	
	//변수 선언
	String name = "";			//이름
	String age = "";			//나이
	String filename = "";		//첨부파일명
	String orgfilename = "";	//첨부파일명
	
	//request -> MultipartRequest -> 객체 생성
	try { 
		//MultipartRequest 객체를 만드는 순간  이미 첨부파일은 files에 복사가 이루어짐
		MultipartRequest multi = new MultipartRequest(request, 			//원래 request
													  path,				//파일 업로드 위치
													  size,				//파일 크기
													  "UTF-8",			//인코딩
													  new DefaultFileRenamePolicy()		//첨부파일 관리(중복 -> 넘버링)
													  );
		//데이터 수신
		//name = request.getParameter("name");
		name = multi.getParameter("name");			//동작O
		name = multi.getParameter("age");
		
		//업로드 파일 정보 -> 파일명
		//<input type="file" name="attach">
		filename = multi.getFilesystemName("attach"); 
		orgfilename = multi.getOriginalFileName("attach");
		
	} catch(Exception e){
		e.printStackTrace();
	}
	
	
	
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ex16_ok.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://pinnpublic.dothome.co.kr/cdn/example-min.css\">\r\n");
      out.write("<style></style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>RESULT</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("		name : ");
      out.print( name );
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		age : ");
      out.print( age );
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		filename : ");
      out.print( filename );
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		orgfilename : ");
      out.print( orgfilename );
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<h2>파일 다운로드</h2>\r\n");
      out.write("	<!-- \r\n");
      out.write("		장점 : 간단함\r\n");
      out.write("		단점 : 파일 확장자에 따라 다름(다운로드 or 뷰어)\r\n");
      out.write("	 -->\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"/jsp//files/");
      out.print( filename );
      out.write('"');
      out.write('>');
      out.print( orgfilename );
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- \r\n");
      out.write("		장점 : 간단함. 모든 파일을 무조건 다운로드 시키는 옵션\r\n");
      out.write("		단점 : 파일명이 다를 수 있다.(넘버링)\r\n");
      out.write("	 -->\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"/jsp//files/");
      out.print( filename );
      out.write("\" download>");
      out.print( orgfilename );
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- \r\n");
      out.write("		장점 : 무조건 다운로드처리, 원본 파일명으로 다운로드\r\n");
      out.write("		단점 : 비용(download.jsp)\r\n");
      out.write("	 -->\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"download.jsp?filename=");
      out.print( filename );
      out.write("&orgfilename=");
      out.print( orgfilename );
      out.write('"');
      out.write('>');
      out.print( orgfilename );
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- https://releases.jquery.com/ -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("	<!-- https://github.com/pinnpublic/cdn -->\r\n");
      out.write("	<script src=\"http://pinnpublic.dothome.co.kr/cdn/example-min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
